# Generated by Django 2.2.3 on 2019-08-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ImageField(upload_to='', verbose_name='产品id')),
                ('name', models.CharField(max_length=32, verbose_name='产品名')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 8, 16, 14, 56, 21, 608832), verbose_name='添加时间')),
            ],
        ),
    ]
