# Generated by Django 2.2.3 on 2019-08-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190816_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vueapi',
            name='number',
            field=models.IntegerField(verbose_name='产品id'),
        ),
    ]
